[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = '''
      default-src 'self' 'unsafe-inline' 'unsafe-eval';
      connect-src 'self' *.firebaseio.com *.googleapis.com;
      img-src 'self' data: blob: https:;
      media-src 'self' blob:;
      style-src 'self' 'unsafe-inline';
      font-src 'self';
      frame-src 'self';
    '''