[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

[[headers]]
  for = "/*.js"
    [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/*.mjs"
    [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/*.ts"
    [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/*.tsx"
    [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/*"
    [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self' 'unsafe-inline' 'unsafe-eval' *.netlify.app; connect-src 'self' *.firebaseio.com *.googleapis.com; img-src 'self' data: blob: https:; media-src 'self' blob:;"